### ISSUE TITLE
Notify long term release plan and roadmap

### ISSUE THREAD

**Issue by davedev42** [kawoou/AnyDate#13]
I think, this project's maintainer @Kawoou has to notify to everyone, the Long Term Release Plan.

I guess that you have quite much more ideas about Swift's useful Date & Time Library, so please tell us your roadmap.

**Comment by davedev42** [comment]
And than, @KoMinkyu , I guess that my English writing is awful. If there's something wrong, please correct.

**Comment by Kawoou** [comment]
Firstly I amend that incorrectly displayed Code Coverage Rate.
After that, I intend to implement known issues and increase the test code until next release.

There is no big change, so next release seems good at 08/22.
And how about version 1.0.1?
