### ISSUE TITLE
LocalDate/Time Comparables logic error

### ISSUE THREAD

**Issue by ddcrobert** [kawoou/AnyDate#15]
I found an error within LocalTime, probably concern LocalDate/LocalDateTime as well.
Given two times: 
17:50:23:372247993 > 17:57:39:0 will return true
Left is clearly before, however, since left nano is greater than right nano, left will be wrongly considered superior.

**Comment by kawoou** [comment]
Thank you for reporting.
That it was completely my coding mistake :(
Please review the solution #16.

This is a critical issue, so we will proceed with the hot fix release.

**Comment by kawoou** [comment]
@ddcrobert 

Cocoapods v1.0.3 released!
Thank you again for letting us know about the critical issue.
Once the CI build is complete, you can use Carthage.
