### ISSUE TITLE
Make value types conform to Hashable

### ISSUE THREAD

**Issue by mattlogan** [kawoou/AnyDate#22]
Value types like `LocalDate` should conform to the `Hashable` protocol so they can be used as dictionary keys.

We could just take the implementation directly from the `hashCode()` methods in `java.time`. For example, `java.time.LocalDate` has the following implementation of `hashCode()`:

```
public int hashCode() {
  int yearValue = this.year;
  int monthValue = this.month;
  int dayValue = this.day;
  return yearValue & -2048 ^ (yearValue << 11) + (monthValue << 6) + dayValue;
}
```

**Comment by kawoou** [comment]
Released v1.0.6
